[package]
name = "yashsriram"
version = "0.0.0"
edition = "2021"
authors = ["Yashasvi Sriram Patkuri <yash.3997@gmail.com>"]

[dependencies]
rand = "0.8.5"
ordered-float = "2.8.0"
bevy = "0.10.1"
bevy_flycam = "0.10.1"
